#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
# export GTK_IM_MODULE=ibus
# export XMODIFIERS=@im=ibus
# export QT_IM_MODULE=ibus
# ibus-daemon -d -x
# export LANG=zh_CN.UTF-8
# LANG="en_US.UTF-8"

# export XDG_CURRENT_DESKTOP=KDE
# which fcitx && (fcitx &)
# which volumeicon && (volumeicon &)

# [[ -f ~/.xprofile.d/xmodmaprc ]] && xmodmap ~/.xprofile.d/xmodmaprc #disabled by input method

# To resolve the problem that mouse wheel doesn't work with gtk3 applications (gentoo)
export GDK_CORE_DEVICE_EVENTS=1


[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.Xresources.d/custom ] && xrdb -merge ~/.Xresources.d/custom
[ -f ~/.xprofile.d/xcustomrc ] && . ~/.xprofile.d/xcustomrc

eval "$(dbus-launch --sh-syntax --exit-with-session)"

# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session awesome
# exec dbus-launch --exit-with-session startplasma-x11
# exec dbus-launch --exit-with-session startplasma-wayland
# export KDEWM=awesome
# exec ~/.stumpwm.d/bin/stumpwm
# exec awesome
# exec enlightenment_start
# exec gnome-session
# exec startkde 
# exec startxfce4
# exec startlxde
# exec startfluxbox 
# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session fvwm
