import = [
    "~/.config/alacritty/alacritty-theme.toml"
]


[font]
normal= { family = "Cascadia Code", style = "Regular" }
# normal = { family = "Source Code Pro", style = "SemiBold" }
size = 13

[window]
opacity = 0.88
startup_mode = "Maximized"

[scrolling]
history = 100000
