#!/bin/sh
__my_setup_conda() {
  if [[ ! -d $1 ]]; then
    return
  fi
  prefix=$(realpath $1)
  environment=$2
  argc=$#
  if [ -f ${prefix}/etc/profile.d/conda.sh ]; then
    . ${prefix}/etc/profile.d/conda.sh
  fi

  if [[ ${argc} -lt 2 ]]; then
    return
  elif [[ -n ${environment} ]]; then
    pythondir=${prefix}/envs/${environment}/bin
  else
    pythondir=${prefix}/bin
  fi

  pythonprefix=$(dirname ${prefix})/anaconda-python
  pythoncommands=(python pip pydoc pytest pyvenv black blackd)
  mkdir -p ${pythonprefix}
  for item in ${pythoncommands[@]}; do
    if [[ -x ${pythondir}/${item} ]]; then
      ln -sfn ${pythondir}/${item} ${pythonprefix}/${item}
    fi
  done
  export PATH=${pythonprefix}:${PATH}
}

__my_find_conda() {
  conda_paths=(
    ~/.local/miniconda3
    /opt/homebrew/Caskroom/miniconda/base
    ~/.local/anaconda3
    /opt/homebrew/anaconda
  )

  for conda_dir in ${conda_paths}; do
    if [ -d $conda_dir ]; then
      echo $conda_dir
      break
    fi
  done
}

__my_setup_conda $(__my_find_conda)

unset -f __my_find_conda
unset -f __my_setup_conda
