#!/bin/sh
function __my_setup_conda() {
  if [[ ! -d $1 ]]; then
    return
  fi
  prefix=$(realpath $1)
  environment=$2
  argc=$#
  if [ -f ${prefix}/etc/profile.d/conda.sh ]; then
    . ${prefix}/etc/profile.d/conda.sh
  fi

  if [[ ${argc} -lt 2 ]]; then
    return
  elif [[ -n ${environment} ]]; then
    pythondir=${prefix}/envs/${environment}/bin
  else
    pythondir=${prefix}/bin
  fi

  pythonprefix=$(dirname ${prefix})/anaconda-python
  pythoncommands=(python pip pydoc pytest pyvenv black blackd)
  mkdir -p ${pythonprefix}
  for item in ${pythoncommands[@]}; do
    if [[ -x ${pythondir}/${item} ]]; then
      ln -sfn ${pythondir}/${item} ${pythonprefix}/${item}
    fi
  done
  export PATH=${pythonprefix}:${PATH}
}

__my_setup_conda ~/.local/anaconda3
__my_setup_conda /opt/homebrew//anaconda3

unset -f __my_setup_conda
