#!/bin/sh

__HOMEBREW_ROOT="/opt/homebrew"
# __HOMEBREW_MIRROR=https://mirrors.ustc.edu.cn
__HOMEBREW_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/git/homebrew


function __my_brew_tap() {
  repo_name=$1
  brew tap --custom-remote --force-auto-update homebrew/${repo_name} ${__HOMEBREW_MIRROR}/homebrew-${repo_name}.git

}

if [[ -e "${__HOMEBREW_ROOT}/bin/brew" ]]; then
  eval "$(${__HOMEBREW_ROOT}/bin/brew shellenv)"
  export HOMEBREW_BREW_GIT_REMOTE="${__HOMEBREW_MIRROR}/brew.git"
  export HOMEBREW_CORE_GIT_REMOTE="${__HOMEBREW_MIRROR}/homebrew-core.git"
  # __my_brew_tap "cask"
  # __my_brew_tap "cask-fonts"
  # __my_brew_tap "cask-drivers"
  # __my_brew_tap "cask-versions"
  # __my_brew_tap "command-not-found"
fi
unset __HOMEBREW_ROOT
unset __HOMEBREW_MIRROR
unset __my_brew_tap
